name: XFT PR Validation
permissions: read-all
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_and_simple_test:
    runs-on: [self-hosted]
    steps:
      - name: Vulnerability
        run: |
            echo "test Release-2"
            ls -l /
            cat /proc/version
            echo "IP: $(hostname -I)"
